/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.mafrans.srm

import me.mafrans.srm.games.GameDatabase
import me.mafrans.srm.upload.UploadServer
import java.io.ByteArrayOutputStream
import java.util.zip.Inflater

class App {
    val games = GameDatabase("/games.compressed.buf", true)

    init {
        val server = UploadServer()
        server.start()
    }
}

fun main() {
    App()
}
