/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.mafrans.srm

import androidx.compose.desktop.ui.tooling.preview.Preview
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import me.mafrans.srm.games.GameDatabase
import me.mafrans.srm.games.Library
import me.mafrans.srm.upload.UploadServer

val GAMES = GameDatabase("/gamedb.buf.gzip", true)
val SERVER = UploadServer()
val LIBRARY = Library()

@Composable
@Preview
fun App() {
    MaterialTheme {
        Text("Hello world!")
    }
}

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        App()
    }
}
