/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.mafrans.srm

import me.mafrans.srm.games.GameDatabase
import me.mafrans.srm.games.Library
import me.mafrans.srm.upload.UploadServer

class App {
    val server = UploadServer()
    val games = GameDatabase("/gamedb.buf.gzip", true)
    val library = Library()

    fun start() {
        server.start()
    }
}

val app = App()

fun main() {
    app.start()
}
