package me.mafrans.srm.games

/**
 * A list of consoles scraped from libretro's db, a console's existence
 * in this list does not indicate that it is supported by the program.
 *
 * @see <a href=https://db.libretro.com/>https://db.libretro.com/</a>
 */
enum class Console(val title: String) {
    AMSTRAD_CPC("Amstrad - CPC"),
    ATARI_5200("Atari - 5200"),
    ATARI_7800("Atari - 7800"),
    ATARI_JAGUAR("Atari - Jaguar"),
    ATARI_LYNX("Atari - Lynx"),
    ATARI_ST("Atari - ST"),
    BANDAI_WONDERSWAN("Bandai - WonderSwan"),
    BANDAI_WONDERSWAN_COLOR("Bandai - WonderSwan Color"),
    CANNONBALL("Cannonball"),
    CASIO_LOOPY("Casio - Loopy"),
    CASIO_PV_1000("Casio - PV-1000"),
    CAVE_STORY("Cave Story"),
    CHAILOVE("ChaiLove"),
    COLECO_COLECOVISION("Coleco - ColecoVision"),
    COMMODORE_64("Commodore - 64"),
    COMMODORE_AMIGA("Commodore - Amiga"),
    COMMODORE_PLUS_4("Commodore - Plus-4"),
    COMMODORE_VIC_20("Commodore - VIC-20"),
    DOOM("DOOM"),
    DOS("DOS"),
    DINOTHAWR("Dinothawr"),
    EMERSON_ARCADIA_2001("Emerson - Arcadia 2001"),
    ENTEX_ADVENTURE_VISION("Entex - Adventure Vision"),
    EPOCH_SUPER_CASSETTE_VISION("Epoch - Super Cassette Vision"),
    FBNEO_ARCADE_GAMES("FBNeo - Arcade Games"),
    FAIRCHILD_CHANNEL_F("Fairchild - Channel F"),
    FLASHBACK("Flashback"),
    FUNTECH_SUPER_ACAN("Funtech - Super Acan"),
    GCE_VECTREX("GCE - Vectrex"),
    GAMEPARK_GP32("GamePark - GP32"),
    HANDHELD_ELECTRONIC_GAME("Handheld Electronic Game"),
    HARTUNG_GAME_MASTER("Hartung - Game Master"),
    LEAPFROG_LEAPSTER_LEARNING_GAME_SYSTEM("LeapFrog - Leapster Learning Game System"),
    LUTRO("Lutro"),
    MAME("MAME"),
    MAME_2000("MAME 2000"),
    MAME_2003("MAME 2003"),
    MAME_2003_PLUS("MAME 2003-Plus"),
    MAME_2010("MAME 2010"),
    MAME_2015("MAME 2015"),
    MAME_2016("MAME 2016"),
    MAGNAVOX_ODYSSEY2("Magnavox - Odyssey2"),
    MATTEL_INTELLIVISION("Mattel - Intellivision"),
    MICROSOFT_MSX("Microsoft - MSX"),
    MICROSOFT_MSX2("Microsoft - MSX2"),
    MICROSOFT_XBOX("Microsoft - Xbox"),
    MRBOOM("MrBoom"),
    NEC_PC_ENGINE_TURBOGRAFX_16("NEC - PC Engine - TurboGrafx 16"),
    NEC_PC_ENGINE_CD_TURBOGRAFX_CD("NEC - PC Engine CD - TurboGrafx-CD"),
    NEC_PC_ENGINE_SUPERGRAFX("NEC - PC Engine SuperGrafx"),
    NEC_PC_FX("NEC - PC-FX"),
    NINTENDO_FAMILY_COMPUTER_DISK_SYSTEM("Nintendo - Family Computer Disk System"),
    NINTENDO_GAME_BOY("Nintendo - Game Boy"),
    NINTENDO_GAME_BOY_ADVANCE("Nintendo - Game Boy Advance"),
    NINTENDO_GAME_BOY_COLOR("Nintendo - Game Boy Color"),
    NINTENDO_GAMECUBE("Nintendo - GameCube"),
    NINTENDO_NINTENDO_3DS("Nintendo - Nintendo 3DS"),
    NINTENDO_NINTENDO_3DS_DIGITAL("Nintendo - Nintendo 3DS (Digital)"),
    NINTENDO_NINTENDO_64("Nintendo - Nintendo 64"),
    NINTENDO_NINTENDO_64DD("Nintendo - Nintendo 64DD"),
    NINTENDO_NINTENDO_DS("Nintendo - Nintendo DS"),
    NINTENDO_NINTENDO_DS_DOWNLOAD_PLAY("Nintendo - Nintendo DS (Download Play)"),
    NINTENDO_NINTENDO_DS_DOWNLOAD_PLAY_BETA("Nintendo - Nintendo DS (Download Play) (BETA)"),
    NINTENDO_NINTENDO_DSI("Nintendo - Nintendo DSi"),
    NINTENDO_NINTENDO_DSI_DIGITAL("Nintendo - Nintendo DSi (Digital)"),
    NINTENDO_NINTENDO_DSI_DECRYPTED("Nintendo - Nintendo DSi Decrypted"),
    NINTENDO_NINTENDO_ENTERTAINMENT_SYSTEM("Nintendo - Nintendo Entertainment System"),
    NINTENDO_POKEMON_MINI("Nintendo - Pokemon Mini"),
    NINTENDO_SATELLAVIEW("Nintendo - Satellaview"),
    NINTENDO_SUFAMI_TURBO("Nintendo - Sufami Turbo"),
    NINTENDO_SUPER_NINTENDO_ENTERTAINMENT_SYSTEM("Nintendo - Super Nintendo Entertainment System"),
    NINTENDO_VIRTUAL_BOY("Nintendo - Virtual Boy"),
    NINTENDO_WII("Nintendo - Wii"),
    NINTENDO_WII_DIGITAL("Nintendo - Wii (Digital)"),
    NINTENDO_E_READER("Nintendo - e-Reader"),
    PHILIPS_VIDEOPAC_PLUS("Philips - Videopac+"),
    QUAKE("Quake"),
    RCA_STUDIO_II("RCA - Studio II"),
    RPG_MAKER("RPG Maker"),
    RICK_DANGEROUS("Rick Dangerous"),
    SNK_NEO_GEO_CD("SNK - Neo Geo CD"),
    SNK_NEO_GEO_POCKET("SNK - Neo Geo Pocket"),
    SNK_NEO_GEO_POCKET_COLOR("SNK - Neo Geo Pocket Color"),
    SCUMMVM("ScummVM"),
    SEGA_32X("Sega - 32X"),
    SEGA_DREAMCAST("Sega - Dreamcast"),
    SEGA_GAME_GEAR("Sega - Game Gear"),
    SEGA_MASTER_SYSTEM_MARK_III("Sega - Master System - Mark III"),
    SEGA_MEGA_DRIVE_GENESIS("Sega - Mega Drive - Genesis"),
    SEGA_MEGA_CD_SEGA_CD("Sega - Mega-CD - Sega CD"),
    SEGA_PICO("Sega - PICO"),
    SEGA_SG_1000("Sega - SG-1000"),
    SEGA_SATURN("Sega - Saturn"),
    SHARP_X68000("Sharp - X68000"),
    SINCLAIR_ZX_81("Sinclair - ZX 81"),
    SINCLAIR_ZX_SPECTRUM("Sinclair - ZX Spectrum"),
    SINCLAIR_ZX_SPECTRUM_PLUS_3("Sinclair - ZX Spectrum +3"),
    SONY_PLAYSTATION("Sony - PlayStation"),
    SONY_PLAYSTATION_2("Sony - PlayStation 2"),
    SONY_PLAYSTATION_3("Sony - PlayStation 3"),
    SONY_PLAYSTATION_3_DOWNLOADABLE("Sony - PlayStation 3 (Downloadable)"),
    SONY_PLAYSTATION_3_PSN_("Sony - PlayStation 3 (PSN)"),
    SONY_PLAYSTATION_PORTABLE("Sony - PlayStation Portable"),
    SONY_PLAYSTATION_PORTABLE_PSN("Sony - PlayStation Portable (PSN)"),
    SONY_PLAYSTATION_PORTABLE_PSX2PSP("Sony - PlayStation Portable (PSX2PSP)"),
    SONY_PLAYSTATION_PORTABLE_UMD_MUSIC("Sony - PlayStation Portable (UMD Music)"),
    SONY_PLAYSTATION_PORTABLE_UMD_VIDEO("Sony - PlayStation Portable (UMD Video)"),
    TIC_80("TIC-80"),
    THE_3DO_COMPANY_3DO("The 3DO Company - 3DO"),
    THOMSON_MOTO("Thomson - MOTO"),
    TIGER_GAME_DOT_COM("Tiger - Game.com"),
    TOMB_RAIDER("Tomb Raider"),
    UZEBOX("Uzebox"),
    VTECH_CREATIVISION("VTech - CreatiVision"),
    VTECH_V_DOT_SMILE("VTech - V.Smile"),
    WATARA_SUPERVISION("Watara - Supervision"),
    OTHER("Other Consoles");

    companion object {
        fun byTitle(title: String): Console {
            return entries.firstOrNull { it.title == title } ?: OTHER
        }
    }
}